### ISSUE TITLE
Can't build custom components in production mode

### ISSUE THREAD

**Issue by dongcp87** [bpmn-io/form-js-examples#11]
### Describe the Bug

Can't build custom components in production mode

### Steps to Reproduce

1. open webpack.config.js in custom-components
2. change mode to production
3. npm start
4. Uncaught Error: No provider for "e"! (Resolving: rangeField -> e)

### Environment

- Host Chrome
- OS: Macos
- Library version: 1.6.4

**Comment by maximryzhov** [comment]
I can confirm this is still happening with library version == 1.8.3.
Error occurs in production mode, only if `optimization.minimize` set to `true` in webpack.conf.js

**Comment by dongcp87** [comment]
@maximryzhov custom-components/app/extension/render/index.js add: 
`CustomFormFields.$inject = ['formFields'];`
