### ISSUE TITLE
Viewer example in Angular

### ISSUE THREAD

**Issue by falko** [bpmn-io/form-js-examples#2]
How would the form-js viewer be integrated with [Angular forms](https://angular.io/guide/forms-overview)?

My current customer has already built a custom tasklist for Camunda Platform using Angular. They already have Camunda's REST API integrated to query and complete tasks. For very simple forms, it would be great to design them using form-js as it is included in Camunda Modeler. One could then imagine letting the form keys of the user tasks reference the JSON form definitions for the tasklist to load them.

Could you provide a code example of how the form-js viewer would interact with the Angular programming model?

**Comment by nikku** [comment]
I assume we're talking about a recent version of Angular here, not AngularJS 1.x, right?

**Comment by nikku** [comment]
What you're asking here is two distinct questions:

> How would the form-js viewer be integrated with Angular forms?

It cannot easily be integrated, as of now. At least we did not attempt such integration yet and we'd need more information (i.e. a basic CodeSandbox that shares a simple use of Angular forms, dedicated requirements) before it makes sense for us to do so.

> Could you provide a code example of how the form-js viewer would interact with the Angular programming model?

In Angular, like most other UI libraries you can get hold on [actual DOM element references](https://angular.io/api/core/ElementRef). See also [example](https://www.techiediaries.com/angular-elementref/). Once you did that you can instantiate form-js on that node. Using the form-js API you can hook up with the Angular life-cycle.
